package com.cursee.more_bows_and_arrows.core.registry;

import com.cursee.more_bows_and_arrows.core.entity.TieredArrowEntity;
import com.cursee.more_bows_and_arrows.core.tier.ArrowTier;
import net.fabricmc.fabric.api.object.builder.v1.entity.FabricEntityTypeBuilder;
import net.minecraft.world.entity.EntityDimensions;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;

public class ModEntityTypesFabric {

    public static void register() {}

    public static final EntityType<TieredArrowEntity> AMETHYST_ARROW = RegistryFabric.registerEntityType("amethyst_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.AMETHYST)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> BAMBOO_ARROW = RegistryFabric.registerEntityType("bamboo_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.BAMBOO)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> BLAZE_ROD_ARROW = RegistryFabric.registerEntityType("blaze_rod_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.BLAZE_ROD)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> BONE_ARROW = RegistryFabric.registerEntityType("bone_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.BONE)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> CACTUS_ARROW = RegistryFabric.registerEntityType("cactus_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.CACTUS)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> COAL_ARROW = RegistryFabric.registerEntityType("coal_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.COAL)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> COPPER_ARROW = RegistryFabric.registerEntityType("copper_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.COPPER)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> DIAMOND_ARROW = RegistryFabric.registerEntityType("diamond_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.DIAMOND)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> DRAGON_BREATH_ARROW = RegistryFabric.registerEntityType("dragon_breath_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.DRAGON_BREATH)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> DRIPSTONE_ARROW = RegistryFabric.registerEntityType("dripstone_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.DRIPSTONE)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> ECHO_ARROW = RegistryFabric.registerEntityType("echo_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.ECHO)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> EGG_ARROW = RegistryFabric.registerEntityType("egg_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.EGG)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> EMERALD_ARROW = RegistryFabric.registerEntityType("emerald_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.EMERALD)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> ENDER_PEARL_ARROW = RegistryFabric.registerEntityType("ender_pearl_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.ENDER_PEARL)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> FIREWORK_ARROW = RegistryFabric.registerEntityType("firework_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.FIREWORK)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> FIRE_CHARGE_ARROW = RegistryFabric.registerEntityType("fire_charge_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.FIRE_CHARGE)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> FLINT_ARROW = RegistryFabric.registerEntityType("flint_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.FLINT)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> FLINT_AND_STEEL_ARROW = RegistryFabric.registerEntityType("flint_and_steel_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.FLINT_AND_STEEL)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> GLOW_INK_SAC_ARROW = RegistryFabric.registerEntityType("glow_ink_sac_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.GLOW_INK_SAC)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> GOLD_ARROW = RegistryFabric.registerEntityType("gold_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.GOLD)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> ICE_ARROW = RegistryFabric.registerEntityType("ice_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.ICE)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> INK_SAC_ARROW = RegistryFabric.registerEntityType("ink_sac_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.INK_SAC)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> IRON_ARROW = RegistryFabric.registerEntityType("iron_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.IRON)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> LADDER_ARROW = RegistryFabric.registerEntityType("ladder_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.LADDER)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> LAPIS_ARROW = RegistryFabric.registerEntityType("lapis_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.LAPIS)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> LIGHTNING_ROD_ARROW = RegistryFabric.registerEntityType("lightning_rod_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.LIGHTNING_ROD)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> NETHERITE_ARROW = RegistryFabric.registerEntityType("netherite_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.NETHERITE)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> NETHER_QUARTZ_ARROW = RegistryFabric.registerEntityType("nether_quartz_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.NETHER_QUARTZ)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> NETHER_STAR_ARROW = RegistryFabric.registerEntityType("nether_star_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.NETHER_STAR)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> OBSIDIAN_ARROW = RegistryFabric.registerEntityType("obsidian_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.OBSIDIAN)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> PAPER_ARROW = RegistryFabric.registerEntityType("paper_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.PAPER)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> PRISMARINE_ARROW = RegistryFabric.registerEntityType("prismarine_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.PRISMARINE)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> REDSTONE_ARROW = RegistryFabric.registerEntityType("redstone_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.REDSTONE)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> SHEAR_ARROW = RegistryFabric.registerEntityType("shear_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SHEAR)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> SHULKER_SHELL_ARROW = RegistryFabric.registerEntityType("shulker_shell_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SHULKER_SHELL)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> SLIMEBALL_ARROW = RegistryFabric.registerEntityType("slimeball_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SLIMEBALL)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> SMOKING_ARROW = RegistryFabric.registerEntityType("smoking_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SMOKING)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> SNOWBALL_ARROW = RegistryFabric.registerEntityType("snowball_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SNOWBALL)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> TNT_ARROW = RegistryFabric.registerEntityType("tnt_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.TNT)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
    public static final EntityType<TieredArrowEntity> WATER_BOTTLE_ARROW = RegistryFabric.registerEntityType("water_bottle_arrow", () -> FabricEntityTypeBuilder.<TieredArrowEntity>create(MobCategory.MISC, (entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.WATER_BOTTLE)).dimensions(EntityDimensions.fixed(0.5f, 0.5f)).trackRangeBlocks(4).trackedUpdateRate(20).build());
}
