package com.cursee.more_bows_and_arrows.core.registry;

import com.cursee.more_bows_and_arrows.core.entity.TieredArrowEntity;
import com.cursee.more_bows_and_arrows.core.tier.ArrowTier;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;

public class ModEntityTypesFabric {

    public static void register() {}

    public static final EntityType<TieredArrowEntity> AMETHYST_ARROW = RegistryFabric.registerEntityType("amethyst_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.AMETHYST), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> BAMBOO_ARROW = RegistryFabric.registerEntityType("bamboo_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.BAMBOO), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> BLAZE_ROD_ARROW = RegistryFabric.registerEntityType("blaze_rod_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.BLAZE_ROD), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> BONE_ARROW = RegistryFabric.registerEntityType("bone_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.BONE), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> CACTUS_ARROW = RegistryFabric.registerEntityType("cactus_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.CACTUS), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> COAL_ARROW = RegistryFabric.registerEntityType("coal_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.COAL), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> COPPER_ARROW = RegistryFabric.registerEntityType("copper_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.COPPER), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> DIAMOND_ARROW = RegistryFabric.registerEntityType("diamond_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.DIAMOND), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> DRAGON_BREATH_ARROW = RegistryFabric.registerEntityType("dragon_breath_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.DRAGON_BREATH), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> DRIPSTONE_ARROW = RegistryFabric.registerEntityType("dripstone_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.DRIPSTONE), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> ECHO_ARROW = RegistryFabric.registerEntityType("echo_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.ECHO), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> EGG_ARROW = RegistryFabric.registerEntityType("egg_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.EGG), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> EMERALD_ARROW = RegistryFabric.registerEntityType("emerald_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.EMERALD), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> ENDER_PEARL_ARROW = RegistryFabric.registerEntityType("ender_pearl_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.ENDER_PEARL), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> FIREWORK_ARROW = RegistryFabric.registerEntityType("firework_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.FIREWORK), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> FIRE_CHARGE_ARROW = RegistryFabric.registerEntityType("fire_charge_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.FIRE_CHARGE), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> FLINT_ARROW = RegistryFabric.registerEntityType("flint_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.FLINT), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> FLINT_AND_STEEL_ARROW = RegistryFabric.registerEntityType("flint_and_steel_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.FLINT_AND_STEEL), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> GLOW_INK_SAC_ARROW = RegistryFabric.registerEntityType("glow_ink_sac_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.GLOW_INK_SAC), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> GOLD_ARROW = RegistryFabric.registerEntityType("gold_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.GOLD), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> ICE_ARROW = RegistryFabric.registerEntityType("ice_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.ICE), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> INK_SAC_ARROW = RegistryFabric.registerEntityType("ink_sac_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.INK_SAC), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> IRON_ARROW = RegistryFabric.registerEntityType("iron_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.IRON), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> LADDER_ARROW = RegistryFabric.registerEntityType("ladder_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.LADDER), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> LAPIS_ARROW = RegistryFabric.registerEntityType("lapis_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.LAPIS), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> LIGHTNING_ROD_ARROW = RegistryFabric.registerEntityType("lightning_rod_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.LIGHTNING_ROD), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> NETHERITE_ARROW = RegistryFabric.registerEntityType("netherite_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.NETHERITE), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> NETHER_QUARTZ_ARROW = RegistryFabric.registerEntityType("nether_quartz_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.NETHER_QUARTZ), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> NETHER_STAR_ARROW = RegistryFabric.registerEntityType("nether_star_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.NETHER_STAR), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> OBSIDIAN_ARROW = RegistryFabric.registerEntityType("obsidian_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.OBSIDIAN), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> PAPER_ARROW = RegistryFabric.registerEntityType("paper_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.PAPER), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> PRISMARINE_ARROW = RegistryFabric.registerEntityType("prismarine_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.PRISMARINE), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> REDSTONE_ARROW = RegistryFabric.registerEntityType("redstone_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.REDSTONE), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> SHEAR_ARROW = RegistryFabric.registerEntityType("shear_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SHEAR), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> SHULKER_SHELL_ARROW = RegistryFabric.registerEntityType("shulker_shell_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SHULKER_SHELL), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> SLIMEBALL_ARROW = RegistryFabric.registerEntityType("slimeball_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SLIMEBALL), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> SMOKING_ARROW = RegistryFabric.registerEntityType("smoking_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SMOKING), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> SNOWBALL_ARROW = RegistryFabric.registerEntityType("snowball_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SNOWBALL), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> TNT_ARROW = RegistryFabric.registerEntityType("tnt_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.TNT), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
    public static final EntityType<TieredArrowEntity> WATER_BOTTLE_ARROW = RegistryFabric.registerEntityType("water_bottle_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.WATER_BOTTLE), MobCategory.MISC).sized(0.5f, 0.5f).clientTrackingRange(4).updateInterval(20).build());
}
