package com.cursee.more_bows_and_arrows.core.registry;

import com.cursee.more_bows_and_arrows.core.entity.TieredArrowEntity;
import com.cursee.more_bows_and_arrows.core.tier.ArrowTier;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.MobCategory;
import net.neoforged.neoforge.registries.DeferredHolder;

public class ModEntityTypesNeoForge {

    public static void register() {}

    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> AMETHYST_ARROW = RegistryNeoForge.registerEntityType("amethyst_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.AMETHYST), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("amethyst_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> BAMBOO_ARROW = RegistryNeoForge.registerEntityType("bamboo_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.BAMBOO), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("bamboo_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> BLAZE_ROD_ARROW = RegistryNeoForge.registerEntityType("blaze_rod_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.BLAZE_ROD), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("blaze_rod_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> BONE_ARROW = RegistryNeoForge.registerEntityType("bone_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.BONE), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("bone_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> CACTUS_ARROW = RegistryNeoForge.registerEntityType("cactus_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.CACTUS), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("cactus_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> COAL_ARROW = RegistryNeoForge.registerEntityType("coal_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.COAL), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("coal_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> COPPER_ARROW = RegistryNeoForge.registerEntityType("copper_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.COPPER), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("copper_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> DIAMOND_ARROW = RegistryNeoForge.registerEntityType("diamond_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.DIAMOND), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("diamond_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> DRAGON_BREATH_ARROW = RegistryNeoForge.registerEntityType("dragon_breath_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.DRAGON_BREATH), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("dragon_breath_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> DRIPSTONE_ARROW = RegistryNeoForge.registerEntityType("dripstone_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.DRIPSTONE), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("dripstone_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> ECHO_ARROW = RegistryNeoForge.registerEntityType("echo_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.ECHO), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("echo_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> EGG_ARROW = RegistryNeoForge.registerEntityType("egg_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.EGG), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("egg_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> EMERALD_ARROW = RegistryNeoForge.registerEntityType("emerald_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.EMERALD), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("emerald_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> ENDER_PEARL_ARROW = RegistryNeoForge.registerEntityType("ender_pearl_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.ENDER_PEARL), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("ender_pearl_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> FIREWORK_ARROW = RegistryNeoForge.registerEntityType("firework_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.FIREWORK), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("firework_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> FIRE_CHARGE_ARROW = RegistryNeoForge.registerEntityType("fire_charge_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.FIRE_CHARGE), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("fire_charge_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> FLINT_ARROW = RegistryNeoForge.registerEntityType("flint_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.FLINT), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("flint_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> FLINT_AND_STEEL_ARROW = RegistryNeoForge.registerEntityType("flint_and_steel_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.FLINT_AND_STEEL), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("flint_and_steel_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> GLOW_INK_SAC_ARROW = RegistryNeoForge.registerEntityType("glow_ink_sac_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.GLOW_INK_SAC), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("glow_ink_sac_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> GOLD_ARROW = RegistryNeoForge.registerEntityType("gold_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.GOLD), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("gold_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> ICE_ARROW = RegistryNeoForge.registerEntityType("ice_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.ICE), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("ice_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> INK_SAC_ARROW = RegistryNeoForge.registerEntityType("ink_sac_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.INK_SAC), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("ink_sac_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> IRON_ARROW = RegistryNeoForge.registerEntityType("iron_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.IRON), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("iron_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> LADDER_ARROW = RegistryNeoForge.registerEntityType("ladder_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.LADDER), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("ladder_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> LAPIS_ARROW = RegistryNeoForge.registerEntityType("lapis_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.LAPIS), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("lapis_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> LIGHTNING_ROD_ARROW = RegistryNeoForge.registerEntityType("lightning_rod_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.LIGHTNING_ROD), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("lightning_rod_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> NETHERITE_ARROW = RegistryNeoForge.registerEntityType("netherite_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.NETHERITE), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("netherite_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> NETHER_QUARTZ_ARROW = RegistryNeoForge.registerEntityType("nether_quartz_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.NETHER_QUARTZ), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("nether_quartz_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> NETHER_STAR_ARROW = RegistryNeoForge.registerEntityType("nether_star_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.NETHER_STAR), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("nether_star_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> OBSIDIAN_ARROW = RegistryNeoForge.registerEntityType("obsidian_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.OBSIDIAN), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("obsidian_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> PAPER_ARROW = RegistryNeoForge.registerEntityType("paper_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.PAPER), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("paper_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> PRISMARINE_ARROW = RegistryNeoForge.registerEntityType("prismarine_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.PRISMARINE), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("prismarine_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> REDSTONE_ARROW = RegistryNeoForge.registerEntityType("redstone_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.REDSTONE), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("redstone_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> SHEAR_ARROW = RegistryNeoForge.registerEntityType("shear_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SHEAR), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("shear_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> SHULKER_SHELL_ARROW = RegistryNeoForge.registerEntityType("shulker_shell_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SHULKER_SHELL), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("shulker_shell_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> SLIMEBALL_ARROW = RegistryNeoForge.registerEntityType("slimeball_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SLIMEBALL), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("slimeball_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> SMOKING_ARROW = RegistryNeoForge.registerEntityType("smoking_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SMOKING), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("smoking_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> SNOWBALL_ARROW = RegistryNeoForge.registerEntityType("snowball_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.SNOWBALL), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("snowball_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> TNT_ARROW = RegistryNeoForge.registerEntityType("tnt_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.TNT), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("tnt_arrow"));
    public static final DeferredHolder<EntityType<?>, EntityType<TieredArrowEntity>> WATER_BOTTLE_ARROW = RegistryNeoForge.registerEntityType("water_bottle_arrow", () -> EntityType.Builder.<TieredArrowEntity>of((entityType, level) -> new TieredArrowEntity(entityType, level, ArrowTier.WATER_BOTTLE), MobCategory.MISC).sized(0.5F, 0.5F).clientTrackingRange(4).updateInterval(20).build("water_bottle_arrow"));
}
